import * as THREE from "three"; import "./style.css";
const S={speed:140,alt:5000,hdg:270,vs:0,selSpd:150,selHdg:270,selVs:0,ap:false,athr:true,gear:false,flaps:0,beacon:false,yaw:0,pitch:0};
const scene=new THREE.Scene();scene.background=new THREE.Color(0x05070a);scene.fog=new THREE.Fog(0x05070a,16,40);
const cam=new THREE.PerspectiveCamera(68,innerWidth/innerHeight,.03,100);cam.position.set(0,1.55,3.15);cam.rotation.order="YXZ";
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:"high-performance"});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;document.body.appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0x9bb0c5,0x17120d,1.7));const sun=new THREE.DirectionalLight(0xffffff,2);sun.position.set(3,5,4);scene.add(sun);
const g=new THREE.Group();scene.add(g);const mat=(c,m=0,r=.7)=>new THREE.MeshStandardMaterial({color:c,metalness:m,roughness:r});const panel=mat(0x181b1e),dark=mat(0x080a0c),metal=mat(0x51565a,.65,.35),screen=mat(0x06151b),green=new THREE.MeshBasicMaterial({color:0x55ff9d});
function box(p,s,m=panel){const o=new THREE.Mesh(new THREE.BoxGeometry(...s),m);o.position.set(...p);o.castShadow=true;g.add(o);return o}function cyl(p,r,h,m=metal){const o=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,20),m);o.position.set(...p);o.castShadow=true;g.add(o);return o}function scr(p,s){const o=new THREE.Mesh(new THREE.PlaneGeometry(...s),screen);o.position.set(...p);o.rotation.x=-.08;g.add(o);return o}
box([0,1.7,1.7],[4,.3,.75]);box([0,1.32,1.72],[4.3,.9,.18]);[-1.45,-.48,.48,1.45].forEach(x=>scr([x,1.47,1.60],[.78,.58]));
box([0,.78,.2],[1.75,.7,2.55]);box([0,1.08,.55],[1.25,.14,1.05],dark);[-.22,.22].forEach(x=>cyl([x,1.2,.55],.055,.42));
box([0,2.65,.1],[4.3,.18,2]);box([-2.35,1.5,.5],[.25,1.9,4]);box([2.35,1.5,.5],[.25,1.9,4]);box([0,.05,.45],[4.8,.1,4.8],dark);
for(let i=0;i<12;i++)cyl([-1.65+(i%6)*.66,2.57,-.25+(i>5?.55:0)],.07,.09);
const buttons=[];function btn(name,p,fn){const o=cyl(p,.075,.1);o.userData.fn=fn;o.userData.name=name;buttons.push(o);return o}
btn("GEAR",[0,.72,-.85],()=>S.gear=!S.gear);btn("BEACON",[-.55,1.1,-.5],()=>S.beacon=!S.beacon);btn("FLAPS+",[.4,1.1,-.5],()=>S.flaps=Math.min(4,S.flaps+1));btn("FLAPS-",[.15,1.1,-.5],()=>S.flaps=Math.max(0,S.flaps-1));
const stickG=new THREE.Group();stickG.position.set(-.95,.85,.85);g.add(stickG);stickG.add(new THREE.Mesh(new THREE.CylinderGeometry(.19,.24,.08,24),dark));const stick=new THREE.Mesh(new THREE.BoxGeometry(.13,.52,.13),metal);stick.position.y=.28;stickG.add(stick);
const ray=new THREE.Raycaster(),ptr=new THREE.Vector2();let looking=false,lx=0,ly=0;renderer.domElement.onpointerdown=e=>{ptr.x=e.clientX/innerWidth*2-1;ptr.y=-(e.clientY/innerHeight)*2+1;ray.setFromCamera(ptr,cam);const h=ray.intersectObjects(buttons)[0];if(h?.object.userData.fn)h.object.userData.fn();looking=true;lx=e.clientX;ly=e.clientY};renderer.domElement.onpointerup=()=>looking=false;renderer.domElement.onpointermove=e=>{if(!looking)return;S.yaw-= (e.clientX-lx)*.0025;S.pitch=Math.max(-.65,Math.min(.4,S.pitch-(e.clientY-ly)*.002));lx=e.clientX;ly=e.clientY};
const hud=document.createElement("div");hud.id="hud";document.body.append(hud);const help=document.createElement("div");help.id="help";help.innerHTML="<b>3D A320 COCKPIT</b><br>DRAG • LOOK AROUND<br>TAP • COCKPIT CONTROLS";document.body.append(help);
function loop(){requestAnimationFrame(loop);if(S.athr)S.speed+=(S.selSpd-S.speed)*.015;if(S.ap){let d=((S.selHdg-S.hdg+540)%360)-180;S.hdg+=d*.015;S.vs+=(S.selVs-S.vs)*.025}S.alt=Math.max(0,S.alt+S.vs/60);cam.rotation.x=S.pitch;cam.rotation.y=S.yaw;hud.innerHTML=`A320neo • COCKPIT<br>SPD ${Math.round(S.speed)} • ALT ${Math.round(S.alt)} • HDG ${String(Math.round(S.hdg)%360).padStart(3,"0")}<br>AP ${S.ap?"ON":"OFF"} • A/THR ${S.athr?"ON":"OFF"} • GEAR ${S.gear?"DOWN":"UP"} • FLAPS ${S.flaps}`;renderer.render(scene,cam)}loop();
window.onresize=()=>{cam.aspect=innerWidth/innerHeight;cam.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)}