import "./style.css";
const state={pitch:0,roll:0,altitude:5000,speed:140,heading:270,vs:0,ap1:false,ap2:false,athr:true,fd:true,selAlt:6000,selSpd:150,selHdg:270,selVs:0,ecam:"ENG",mcdu:"INIT",scratch:"",gear:"UP",flaps:0,parkingBrake:true,beacon:false};
const app=document.querySelector("#app");const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
function button(label,fn,cls=""){const b=document.createElement("button");b.className="key "+cls;b.textContent=label;b.addEventListener("pointerdown",e=>{e.preventDefault();b.classList.add("pressed");fn()});b.addEventListener("pointerup",()=>b.classList.remove("pressed"));b.addEventListener("pointerleave",()=>b.classList.remove("pressed"));return b}
function knob(label,key,step,min,max){const wrap=document.createElement("div");wrap.className="knobbox";const k=document.createElement("div");k.className="knob";k.addEventListener("pointerdown",e=>{k.setPointerCapture(e.pointerId);k.dataset.y=e.clientY});k.addEventListener("pointermove",e=>{if(k.hasPointerCapture(e.pointerId)){const dy=k.dataset.y-e.clientY;if(Math.abs(dy)>8){state[key]=clamp(state[key]+(dy>0?step:-step),min,max);k.dataset.y=e.clientY;render()}}});wrap.append(k,document.createTextNode(label+" "+state[key]));return wrap}
function render(){app.innerHTML=`<main class="cockpit"><header><strong>A320neo SIM</strong><span>SIMULATION • ${state.ap1?"AP1":"MANUAL"}</span></header><section class="displays"><div class="screen pfd"><b>PFD</b><div class="horizon" style="transform:translateY(${state.pitch*3}px) rotate(${state.roll}deg)"></div><span class="speed">${Math.round(state.speed)}</span><span class="alt">${Math.round(state.altitude)}</span><span class="hdg">${String(Math.round(state.heading)%360).padStart(3,"0")}°</span><span class="vs">VS ${Math.round(state.vs)} FPM</span></div><div class="screen nd"><b>ND</b><div class="compass">N<br>${String(Math.round(state.heading)%360).padStart(3,"0")}°<br>S</div><div class="route">✈</div></div><div class="screen ecam"><b>ECAM • ${state.ecam}</b><div class="ecamdata">ENG 1 ${Math.round(state.speed*7)} RPM<br>ENG 2 ${Math.round(state.speed*7)} RPM<br>ELEC • GREEN<br>HYD • GREEN<br>GEAR • ${state.gear}<br>FLAPS • ${state.flaps}</div></div></section><section class="panel fcu"><b>FCU</b><div class="keys" id="fcu"></div><div class="knobs" id="knobs"></div></section><section class="panel mcdu"><b>MCDU</b><div class="mcdu-screen">${state.mcdu}<hr>ACTIVE PAGE<br><small>SPD ${Math.round(state.speed)} / ALT ${Math.round(state.altitude)} / HDG ${String(Math.round(state.heading)%360).padStart(3,"0")}</small><br><small>SCRATCH: ${state.scratch||"—"}</small></div><div class="mcdukeys" id="mcdu"></div></section><section class="panel controls"><b>PEDESTAL</b><div class="keys" id="pedestal"></div><div class="throttles"><label>ENG 1 <input type="range" min="0" max="100" value="${state.speed/3.5}" data-eng="1"></label><label>ENG 2 <input type="range" min="0" max="100" value="${state.speed/3.5}" data-eng="2"></label></div></section><section class="panel stick"><b>SIDESTICK</b><div id="stick" class="stickzone"><div class="stick"></div></div><small>Drag down = nose up • drag up = nose down</small></section></main>`;
const f=document.querySelector("#fcu");["FD","AP1","AP2","A/THR"].forEach(x=>f.append(button(x,()=>{const k=x==="A/THR"?"athr":x.toLowerCase();state[k]=!state[k];render()},(x==="FD"?state.fd:x==="A/THR"?state.athr:state[x.toLowerCase()])?"on":"")));const ks=document.querySelector("#knobs");[["SPD","selSpd",1,100,350],["HDG","selHdg",1,0,359],["ALT","selAlt",100,1000,39000],["VS","selVs",100,-6000,6000]].forEach(a=>ks.append(knob(...a)));
const m=document.querySelector("#mcdu");["INIT","F-PLN","PERF","PROG","DIR","DATA","RAD NAV","CLR","←","→"].forEach(x=>m.append(button(x,()=>{if(x==="CLR")state.scratch="";else if(x==="←")state.scratch=state.scratch.slice(0,-1);else state.mcdu=x;render()})));
const p=document.querySelector("#pedestal");["P/BRAKE","BEACON","GEAR","FLAPS −","FLAPS +"].forEach(x=>p.append(button(x,()=>{if(x==="P/BRAKE")state.parkingBrake=!state.parkingBrake;if(x==="BEACON")state.beacon=!state.beacon;if(x==="GEAR")state.gear=state.gear==="UP"?"DOWN":"UP";if(x==="FLAPS −")state.flaps=clamp(state.flaps-1,0,4);if(x==="FLAPS +")state.flaps=clamp(state.flaps+1,0,4);render()},(x==="P/BRAKE"?state.parkingBrake:x==="BEACON"?state.beacon:false)?"on":"")));
document.querySelectorAll("input[data-eng]").forEach(i=>i.addEventListener("input",e=>{if(!state.athr)state.speed=clamp(Number(e.target.value)*3.5,80,350)}));const z=document.querySelector("#stick"),s=z.querySelector(".stick");let active=false;z.addEventListener("pointerdown",e=>{active=true;z.setPointerCapture(e.pointerId);move(e)});z.addEventListener("pointermove",e=>active&&move(e));z.addEventListener("pointerup",()=>{active=false;s.style.left="50%";s.style.top="50%";state.roll=0;state.pitch=0});function move(e){const r=z.getBoundingClientRect(),x=clamp((e.clientX-r.left)/r.width,0,1),y=clamp((e.clientY-r.top)/r.height,0,1);s.style.left=x*100+"%";s.style.top=y*100+"%";state.roll=(x-.5)*30;state.pitch=(.5-y)*20}}
render();setInterval(()=>{if(state.athr)state.speed+=(state.selSpd-state.speed)*.02;if(state.ap1){let d=((state.selHdg-state.heading+540)%360)-180;state.heading+=d*.02;state.vs+=(state.selVs-state.vs)*.03}state.altitude=clamp(state.altitude+state.vs/60,0,45000);state.speed=clamp(state.speed,70,380);render()},250);